### ISSUE TITLE
Sequential style passing items as args

### ISSUE THREAD

**Issue by Doomerdinger** [hauptmech/odio_urdf#10]
It would be great if when using "sequential style" you could pass in compatible types as args. So a link for a parent for example.

From your example:
```python
my_robot = Robot()
link1 = Link() #name 'link1' will be used unless link1.name is set 

my_robot(link1)

# Standard
base = Parent("link1")
joint1 = Joint(base, Child("link2"), type="continuous") 

# What I propose
joint1 = Joint(link1, Child("link2"), type="continuous") 

# Or
joint1 = Joint(Parent(link1), Child("link2"), type="continuous") 

# Alternatively
base = Parent(link1)
joint1 = Joint(base, Child("link2"), type="continuous") 

my_robot(joint1)

print(my_robot)
```

It can be kind of cumbersome to type out all the various strings of names, when they are already defined by links declared earlier.

This has particular use with how I am trying to use odio where the actual link names can be significantly longer than the logical names.

**Comment by hauptmech** [comment]
For a quick fix `base = Parent(link1.name)` should work.

**Comment by hauptmech** [comment]
Pushed a change to let `Parent` and `Child` extract link names if links are passed in.

So the following will work:
```
# Or
joint1 = Joint(Parent(link1), Child("link2"), type="continuous") 
# Alternatively
base = Parent(link1)
joint1 = Joint(base, Child("link2"), type="continuous") 
```

Please test and let me know if it works as expected.

**Comment by Doomerdinger** [comment]
I'll test it out, thank you

**Comment by Doomerdinger** [comment]
Works great in my admittedly short and simple testing! Thanks.
