### ISSUE TITLE
Load Xacro to Group instead of Robot

### ISSUE THREAD

**Issue by Doomerdinger** [hauptmech/odio_urdf#14]
My issue is a bit more complicated than the title implies, but generally boils down to it.

I am trying to make a robot that pulls from multiple files. Those files provide a `Group` back to the main file which aggregates them in a `Robot` object. Some of those `Group` files are defined entirely with odio, but some compose xacro files into odio by running xacro directly and storing the output.

The `xacro_xml` arg that can be used with `Robot` cannot be used here, as I have to use a group. Or I can use a `Robot` and then discard the top level tags so I can convert it to a `Group` but I can't figure out how to make that happen. 

I've resorted to running xacro,parsing the result in element tree, iterating over it, appending it all to the xmltext of the group, then in the top level file doing 
```python3
my_robot(my_group)
my_robot.xmltext += my_group.xmltext
```
but I'd like the group to be a fully fledged odio object. Am I missing something here?

**Comment by hauptmech** [comment]
Added the capability requested above.

```python
"""
    Test for adding xacro xml to groups
"""
from odio_urdf import *

xmltext1 = """<?xml version="1.0"?>
<robot name="xacro_robot_1" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="bubba"/>
</robot>
"""

xmltext2 = """<?xml version="1.0"?>
<robot name="xacro_robot_2" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="hotep"/>
</robot>
"""

my_robot = Robot( Link( name="link1" ), xacro_xml=xmltext1)

subgroup = Group( Link( name="link2"), xacro_xml=xmltext2)

my_robot(subgroup)

print(my_robot)
```
While other elements will be interleaved in the order they were added, the xacro xml will be appended at the bottom of the output file. I have no idea if this will cause issues for some use cases. Please shout out if it does.
