### ISSUE TITLE
Xacro macro compatibility 

### ISSUE THREAD

**Issue by Doomerdinger** [hauptmech/odio_urdf#7]
I'm curious about how compatible this library is with xacro, specifically concerning macros.

I see there are a couple examples of importing xacro files, but none of those files have macros defined. If an included xacro file has a macro, is there any way for this library to parse that macro and allow the calling of that macro, allowing us to specify xacro macro arguments?

I would like to at least try this tool, but if it can't work with existing xacro macros that provides a significant barrier (as some of the macros I want to use are defined in packages I do not control, and would prefer to not remake them with this tool so any further changes to those external macros are properly updated without additional effort)

**Comment by hauptmech** [comment]
The xacro stuff in this library is for when you want to port xacro xml to the python classes in odio_urdf. If you have 3rd party xacro, you are better off using  xacro directly rather than porting it to this library. There is no problem mixing in the xacro output.

Here's a simple example of adding a franka panda described using xacro to a robot described by odio_urdf.

```python
# source all necessary ros setup.* environments before running this code
import xml.etree.ElementTree as ET
from odio_urdf import *
import subprocess

# Start with a rotating base
my_robot = Robot("panda_with_a_twist",
                Link("swivel_base"),
                Joint("swivel_joint", Parent("swivel_base"), Child("panda_link0"), type="continuous"),
)

# Use xacro to get the franka panda arm URDF.
res = subprocess.run(['rosrun', 'xacro', 'xacro', 'panda_arm.urdf.xacro'], capture_output=True)

# Use your favorite xml tool to navigate the xml tree
root = ET.fromstring(res.stdout)   # The root shoud be <Robot/>

# Grab all the elements from the xacro that we want. In this case all the elements in <Robot>
for child in root:
    my_robot.xmltext += ET.tostring(child,encoding='unicode') # Add the xml to our <Robot>

# All done. Print the URDF.
print(my_robot)

```
The key point is that each object in odio_urdf has an `xmltext` attribute that gets appended to its output when generating the URDF.

**Comment by Doomerdinger** [comment]
I didn't even think about using subprocess, an oversight on my part. Thanks for the reply!

**Comment by hauptmech** [comment]
I added an `xacro_xml` attribute that will walk through and integrate the xacro elements for you. See the readme. Gave the module a much needed cleanup as well.

**Comment by Doomerdinger** [comment]
Wow, thank you! Above and beyond.
