### ISSUE TITLE
bdist_wheel fails after the recent changes

### ISSUE THREAD

**Issue by georgeswani** [hauptmech/odio_urdf#8]
Hi,
I install this package using the below comand for my application

pip install git+https://github.com/hauptmech/odio_urdf.git

It is failing from today with the below error. I am hoping this is due to the recent changes merged. Can you please advise on this ?

Error Message
Looking in indexes: https://pypi.python.org/simple/
Collecting git+https://github.com/hauptmech/odio_urdf.git
  Cloning https://github.com/hauptmech/odio_urdf.git to /tmp/pip-req-build-cteq9uv9
  Running command git clone -q https://github.com/hauptmech/odio_urdf.git /tmp/pip-req-build-cteq9uv9
Building wheels for collected packages: odio-urdf
  Building wheel for odio-urdf (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7pw6de0u
       cwd: /tmp/pip-req-build-cteq9uv9/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/odio_urdf
  copying odio_urdf/__init__.py -> build/lib/odio_urdf
  copying odio_urdf/__main__.py -> build/lib/odio_urdf
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/odio_urdf
  copying build/lib/odio_urdf/__init__.py -> build/bdist.linux-x86_64/wheel/odio_urdf
  copying build/lib/odio_urdf/__main__.py -> build/bdist.linux-x86_64/wheel/odio_urdf
  running install_egg_info
  error: error in 'egg_base' option: '' does not exist or is not a directory
  ----------------------------------------
  ERROR: Failed building wheel for odio-urdf
  Running setup.py clean for odio-urdf
Failed to build odio-urdf
Installing collected packages: odio-urdf
    Running setup.py install for odio-urdf ... error
    ERROR: Command errored out with exit status 1:
     command:venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ofubhb7u/install-record.txt --single-version-externally-managed --compile --install-headers /venv/include/site/python3.6/odio-urdf
         cwd: /tmp/pip-req-build-cteq9uv9/
    Complete output (15 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/odio_urdf
    copying odio_urdf/__init__.py -> build/lib/odio_urdf
    copying odio_urdf/__main__.py -> build/lib/odio_urdf
    running install_lib
    copying build/lib/odio_urdf/__init__.py -> /venv/lib/python3.6/site-packages/odio_urdf
    copying build/lib/odio_urdf/__main__.py -> /venv/lib/python3.6/site-packages/odio_urdf
    byte-compiling /venv/lib/python3.6/site-packages/odio_urdf/__init__.py to __init__.cpython-36.pyc
    byte-compiling /venv/lib/python3.6/site-packages/odio_urdf/__main__.py to __main__.cpython-36.pyc
    running install_egg_info
    error: error in 'egg_base' option: '' does not exist or is not a directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-cteq9uv9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ofubhb7u/install-record.txt --single-version-externally-managed --compile --install-headers

**Comment by hauptmech** [comment]
Thanks for reporting this. I think I have a fix pushed. Please try and let me know.

**Comment by georgeswani** [comment]
Thank you for the quick turn around. The change has fixed the issue.
